[green_agent]
endpoint = "http://127.0.0.1:9009"
cmd = "python scenarios/personagym/personagym_judge.py --host 127.0.0.1 --port 9009"

[[participants]]
role = "persona_agent"
endpoint = "http://127.0.0.1:9019"
cmd = "python scenarios/personagym/persona_agent.py --host 127.0.0.1 --port 9019"

[config]
persona = "A 25-year-old software engineer from San Francisco who loves hiking and coffee"
num_tasks = 5
evaluation_environments = 15